# Import Original Data

In [2]:
import pandas as pd
df = pd.read_csv('data.csv')

In [3]:
df

     WBRatio  OPC  PPC  DAYS   CO2  STRENGTH
0       0.45  400    0     7  0.00     22.57
1       0.45  400    0     7  0.00     29.51
2       0.45  400    0     7  0.00     20.66
3       0.45  400    0     7  0.05     25.30
4       0.45  400    0     7  0.05     24.03
..       ...  ...  ...   ...   ...       ...
265     0.55    0  350    56  0.15     29.66
266     0.55    0  350    56  0.15     29.71
267     0.55    0  350    56  0.20     27.44
268     0.55    0  350    56  0.20     31.58
269     0.55    0  350    56  0.20     25.46

[270 rows x 6 columns]

In [4]:
from pycaret.regression import *

# prompt: Use Darts to predict Strength
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error, r2_score

# Prepare the data
X = df.drop('STRENGTH', axis=1)
y = df['STRENGTH']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


# Create a PyCaret regression experiment
# Added index=False to avoid issues with duplicate indices
reg_exp = setup(data=pd.concat([X, y], axis=1), target='STRENGTH', session_id=123, index=False)

# Predict on unseen data (if you have any)
# predictions = predict_model(tuned_best_model, data=unseen_data)

In [5]:
# Compare different regression models
best_model = compare_models()

In [6]:
# Tune the best model
tuned_best_model = tune_model(best_model)

# Evaluate the tuned model
evaluate_model(tuned_best_model)

Fitting 10 folds for each of 10 candidates, totalling 100 fits

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Pipeline Plot', 'pipelinâ€¦